# Generated by Django 5.0.6 on 2024-06-18 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of item', max_length=200, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, help_text='Enter a detailed description of the item', null=True, verbose_name='Product Description')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, error_messages={'invalid': 'Please enter a valid price', 'null': 'This field cannot be null'}, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10000)], verbose_name='Product Price')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inventories',
                'db_table': 'Inventory',
            },
        ),
    ]
