# Generated by Django 5.0.6 on 2024-06-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your full name', max_length=250, verbose_name='Full Name')),
                ('contact', models.TextField(verbose_name='Contact Information')),
                ('items', models.ManyToManyField(blank=True, null=True, related_name='items_supplied', to='inventory.inventory')),
            ],
        ),
    ]
