# Generated by Django 5.0.6 on 2024-06-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items_supplied', to='inventory.inventory'),
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='Supplier',
        ),
    ]
